spring.datasource.url=jdbc:mysql://localhost:3306/sanos_y_salvos
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.security.user.name=admin
spring.security.user.password=1234
jwt.secret=clave_de_prueba_que_debe_tener_minimo_32_chars
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true