version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-reportes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sanos_y_salvos
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  reportes:
    build: .
    container_name: reportes-backend
    depends_on:
      - mysql
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sanos_y_salvos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  mysql_data: